### PR TITLE
Update port.rb

### PR DESCRIPTION
**Pull request by equick**
Fixed regex to support multiple ports. I've just seen another pull request for this so if that one doesn't go anywhere, feel free to come back to me and I will try looking at the regex again to work with other scenarios.

Ed

### CODE REVIEW

**Comment by BackSlasher** [comment]
Hi and thanks for the PR.
I'll look into it soon, but can I bother you with trying to find weird cases like this
```
$ semanage port -l
...
poorly_tcp_written_1024_descriptor tcp 52
...
```
(taken from other PR) and making sure your regex works OK with them?

**Comment by BackSlasher** [comment]
Sidenote: Maybe instead of `.` we can use something more strict like `(\d+,)` ?

**Comment by equick** [comment]
Definitely ok. I'll take another look at it :)

**Comment by equick** [comment]
How about this?

```
root@ldtdsr000002008 DEV # echo 'http_port_t                    tcp      8013, 8015, 8019, 8005, 8009, 8010, 8000, 8003, 80' | grep -P 'http_port_t\s+tcp\s*(\s\d+,)*\s*80(,|$)'
http_port_t                    tcp      8013, 8015, 8019, 8005, 8009, 8010, 8000, 8003, 80
root@ldtdsr000002008 DEV # echo 'http_port_t                    tcp      8013, 8015, 8019, 8005, 8009, 8010, 8000, 8003, 80' | grep -P 'http_port_t\s+tcp\s*(\s\d+,)*\s*8013(,|$)'
http_port_t                    tcp      8013, 8015, 8019, 8005, 8009, 8010, 8000, 8003, 80
root@ldtdsr000002008 DEV # echo 'http_port_t                    tcp      8013, 8015, 8019, 8005, 8009, 8010, 8000, 8003, 80' | grep -P 'http_port_t\s+tcp\s*(\s\d+,)*\s*8015(,|$)'
http_port_t                    tcp      8013, 8015, 8019, 8005, 8009, 8010, 8000, 8003, 80
root@ldtdsr000002008 DEV # echo 'http_port_t                    tcp      8013, 8015, 8019, 8005, 8009, 8010, 8000, 8003, 80' | grep -P 'http_port_t\s+tcp\s*(\s\d+,)*\s*8019(,|$)'
http_port_t                    tcp      8013, 8015, 8019, 8005, 8009, 8010, 8000, 8003, 80
root@ldtdsr000002008 DEV # echo 'http_port_t                    tcp      80' | grep -P 'http_port_t\s+tcp\s*(\s\d+,)*\s*80(,|$)'
http_port_t                    tcp      80
```

**Comment by BackSlasher** [comment]
Looks neat. Mind updating the code to match that?

**Comment by equick** [comment]
I've created PR #28

**Comment by BackSlasher** [comment]
Could you just reopen this and update the branch? :)

**Comment by equick** [comment]
Sorry about that, my git branch skills are not what they should be :)
How does it look now?

**Comment by BackSlasher** [comment]
Better :)
I'll do some testing of my own. You can try squashing your commits into one and improve the regex slightly.

**Comment by equick** [comment]
What do you mean improve it slightly? And not sure I know how to squash the commits into one. Does that really matter?

**Pull request closed without merging**
