### PR TITLE
Support multiple ports for a single type

### PR DESCRIPTION
**Pull request by Sauraus**
Resolves: https://github.com/BackSlasher/chef-selinuxpolicy/issues/11

### CODE REVIEW

**Comment by BackSlasher** [comment]
This is the problematic part. I'm repeating my previous issue:
Your version has port `1024` matching a context named `mytcp1024blabla`.
We need to modify the regex so it won't. Maybe allow spaces and later numbers and seperators, like `\\s+[\d\\-,]`?

Please write provide some examples here so we can test some regexes (I don't have my servers at the moment)

**Comment by Sauraus** [comment]
```mytcp1024blabla``` can never exist, because the output is determined by semanage port -l which  always looks like this:

[root@selinux_policy-berkshelf vagrant]# semanage port -l|grep http
http_cache_port_t              tcp      3128, 8080, 8118, 8123, 10001-10010
http_cache_port_t              udp      3130
http_port_t                    tcp      80, 81, 443, 488, 8008, 8009, 8443, 9000
pegasus_http_port_t            tcp      5988
pegasus_https_port_t           tcp      5989

What the regex does not and cannot take into account is the ```10001-10010``` above.

**Comment by BackSlasher** [comment]
(Use ``` for multiple lines of code)
Imagine this:
```
$ semanage port -l
...
poorly_tcp_written_1024_descriptor tcp 52
...
```
Now note that `echo 'poorly_tcp_written_1024_descriptor tcp 52' | grep -P 'tcp.*1024'` works
You're right about ranges, too
If you want to give it a more robust treatment, I can see 2 options:

* Move this `not_if` logic to a ruby block, parsing the output in a more sophisticated manner (like splitting by space, treating `arr[1]` as the protocol, `arr[2..-1]` as different port ranges etc.
* Use Python (it has to be installed, since semanage is written in python) and test everything there

**Comment by datallah** [comment]
The following patch is slightly better because it fixes partial matches (the current behavior and the pull request both have an issue in that they'll mistakenly match an assignment for e.g. port 8080 when checking if a an assignment exists for port 80).

It still doesn't address matching ports that are within ranges.

```patch
diff --git a/selinux_policy/providers/port.rb b/selinux_policy/providers/port.rb
--- a/selinux_policy/providers/port.rb
+++ b/selinux_policy/providers/port.rb
@@ -9,7 +9,7 @@
 action :add do
   execute "selinux-port-#{new_resource.port}-add" do
     command "/usr/sbin/semanage port -a -t #{new_resource.secontext} -p #{new_resource.protocol} #{new_resource.port}"
-    not_if "/usr/sbin/semanage port -l | grep -P '#{new_resource.protocol}\\s+#{new_resource.port}'>/dev/null"
+    not_if "/usr/sbin/semanage port -l | grep -P '#{new_resource.protocol}\\s+([0-9-]+,\\s+)*#{new_resource.port}(,\\s+[0-9-]+)*$'>/dev/null"
     only_if {use_selinux}
   end
 end
@@ -18,7 +18,7 @@
 action :delete do
   execute "selinux-port-#{new_resource.port}-delete" do
     command "/usr/sbin/semanage port -d -p #{new_resource.protocol} #{new_resource.port}"
-    only_if "/usr/sbin/semanage port -l | grep -P '#{new_resource.protocol}\\s+#{new_resource.port}'>/dev/null"
+    only_if "/usr/sbin/semanage port -l | grep -P '#{new_resource.protocol}\\s+([0-9-]+,\\s+)*#{new_resource.port}(,\\s+[0-9-]+)*$'>/dev/null"
     only_if {use_selinux}
   end
 end
@@ -33,13 +33,13 @@
 action :addormodify do
   execute "selinux-port-#{new_resource.port}-addormodify" do
     command <<-EOT
-    if /usr/sbin/semanage port -l | grep -P '#{new_resource.protocol}\\s+#{new_resource.port}'>/dev/null; then
+    if /usr/sbin/semanage port -l | grep -P '#{new_resource.protocol}\\s+([0-9-]+,\\s+)*#{new_resource.port}(,\\s+[0-9-]+)*$'>/dev/null; then
       /usr/sbin/semanage port -m -t #{new_resource.secontext} -p #{new_resource.protocol} #{new_resource.port}
     else
       /usr/sbin/semanage port -a -t #{new_resource.secontext} -p #{new_resource.protocol} #{new_resource.port}
     fi
     EOT
-    not_if "/usr/sbin/semanage port -l | grep -P '#{new_resource.secontext}\\s+#{new_resource.protocol}\\s+#{new_resource.port}'>/dev/null"
+    not_if "/usr/sbin/semanage port -l | grep -P '#{new_resource.secontext}\\s+#{new_resource.protocol}\\s+([0-9-]+,\\s+)*#{new_resource.port}(,\\s+[0-9-]+)*$'>/dev/null"
     only_if {use_selinux}
   end
 end
```

**Comment by BackSlasher** [comment]
See #30 - I prefer moving away from `grep`ping

**Pull request closed without merging**
