### PR TITLE
Add ChefSpec matchers

### PR DESCRIPTION
**Pull request by shortdudey123**

### CODE REVIEW

**Comment by BackSlasher** [comment]
Huh? :)

**Comment by shortdudey123** [comment]
@BackSlasher https://github.com/sethvargo/chefspec#packaging-custom-matchers

**Comment by BackSlasher** [comment]
Oh ok. I'm assuming it helps you with testing?

**Comment by shortdudey123** [comment]
Yup, ChefSpec is what most of the Chef community uses for testing chef resources and recipes

https://docs.chef.io/chefspec.html
https://semaphoreci.com/community/tutorials/unit-tests-for-chef-cookbooks-with-chefspec

**Comment by BackSlasher** [comment]
BTW, I'll be happy to see some examples for your tests, both for my own use and to add them to the cookbook

**Comment by shortdudey123** [comment]
Example of opening MongoDB port:

Recipe
```
selinux_policy_port '27018' do
  protocol 'tcp'
  secontext 'mongod_port_t'
end
```

Spec
```
require 'spec_helper'
 
describe 'cookbook::recipe' do 
  let(:chef_run) { ChefSpec::SoloRunner.new.converge(described_recipe) }
 
  it 'set selinux port allowance for mongod on 27018' do
    expect(chef_run).to addormodify_selinux_policy_port('27018').with(
      protocol: 'tcp',
      secontext: 'mongod_port_t'
    )
  end
end
```

**Comment by BackSlasher** [comment]
I see. So it's indeed more useful to validating cookbooks that USE
resources from here than testing THIS cookbook.

Thanks anyway :)

*Nitzan Raz*
http://backslasher.net

**Pull request merged**
