### PR TITLE
Add fcontext resource to manage file contexts.

### PR DESCRIPTION
**Pull request by joerg**
One more try. I think I have everything now. I have no idea why git deletes and inserts you as author and I don't care. Its the same line...

### CODE REVIEW

**Comment by BackSlasher** [comment]
You can rebase your original PR, no need to create new ones :)
Close whichever you like and I'll look at the other one.

**Comment by BackSlasher** [comment]
I'm accepting this but I'll probably mess with your commit a bit. I don't want to do this [chinese whispers](http://en.wikipedia.org/wiki/Chinese_whispers) thing with you because you worked hard and my edits are minute.
I'm told you'll still get the commit credit, and you'll forever be in the README of fame :)

**Comment by joerg** [comment]
Thats what pull requests are for. If I was not happy with you editing my code I would have forked your project. ;)
Btw: Opscode also showed some interest in selinux. Maybe they will fork this project some day. https://github.com/chef-cookbooks/mysql/issues/305

**Comment by BackSlasher** [comment]
Didn't really merge to master, will merge privately

**Comment by BackSlasher** [comment]
Solved the regex issue btw, you have to specify regex type before the regex expression because `find` was designed to annoy people.

**Pull request merged**
