### PR TITLE
Migrated port detection to native python script

### PR DESCRIPTION
**Pull request by BackSlasher**
Solves #30

### CODE REVIEW

**Comment by equick** [comment]
Hi BackSlasher, any plans to merge this into the master and make a new release soon?

**Comment by BackSlasher** [comment]
Hi
Only after someone tests it :)
I didn't get to test this branch in real usage, only in the kitchen thingy.
If you'd care to take it for a run and give me the clear that'd be awesome.

**Comment by equick** [comment]
Sure I will test it this weekend :)

**Comment by BackSlasher** [comment]
Any news @equick ?

**Comment by equick** [comment]
Hi yes but not good news, I got the following error https://gist.github.com/equick/08da87998037b585b75b

**Comment by equick** [comment]
I ran it again after changing this line

-matching_key = find(lambda k: k[0]<=start_port and k[1]>=end_port and k[2]==protocol ,pr.keys())
+matching_key = find(lambda k: k[0]<=port_start and k[1]>=port_end and k[2]==protocol ,pr.keys())

but it broke out again:

https://gist.github.com/equick/da99a509a5091c125030

**Comment by BackSlasher** [comment]
interesting. Well, feel free to branch etc, I'll look at your findings and
try to fix them tomorrow (it's night time here :)

*Nitzan Raz*
http://backslasher.net

**Comment by equick** [comment]
No probs, it's bed time here as well. I haven't looked into it that much tbh but can see it's running your script and exiting with a 2 so that part might be doing what you expected

$ sudo /var/chef/cache/selinux_policy/helper_scripts/port_locate.py tcp 8029
Label mismatch (1024, 32767, 'tcp') unreserved_port_t

Catch you tomorrow :)

**Comment by equick** [comment]
Morning Nitzan,

I've made the following change in ./chef-selinuxpolicy/providers/port.rb and this seems to work.

```
action :addormodify do
  prepare_scripts

  execute "selinux-port-#{new_resource.port}-addormodify" do
    command <<-EOT
    #{port_defined(new_resource.port, new_resource.protocol)}
    if [ $? != 0 ]; then
      /usr/sbin/semanage port -m -t #{new_resource.secontext} -p #{new_resource.protocol} #{new_resource.port}
    else
      /usr/sbin/semanage port -a -t #{new_resource.secontext} -p #{new_resource.protocol} #{new_resource.port}
    fi
    EOT
    not_if { port_defined(new_resource.port, new_resource.protocol, new_resource.secontext) }
    only_if {use_selinux}
  end
end
```

Ed

**Comment by BackSlasher** [comment]
Hi @equick.
I don't understand the last line in the patch. Is this for lazy evaluation?
You think it's better if I give you contributor access so you can update this branch?
PS, I'm thinking about modifying the script to print out the label instead of accepting it and exiting, something like:
```bash
PORT=5678
PROTOCOL=tcp
LABEL=mysql
RES=$(./port_locate.py $PROTOCOL $PORT) && [ "$RES"  == "$LABEL" ] # port is registered to specific label
RES=$(./port_locate.py $PROTOCL $PORT) && [  -n "$RES" ] # port isn't registered
```

**Comment by BackSlasher** [comment]
Made you collaborator, please don't push to master :)

**Comment by equick** [comment]
Thanks for that. Please correct me if I'm wrong as I'm still fairly new at this, but in the last line I put curly brackets round the command otherwise the not_if seemed to fail and ran the execute command, which showed resources being updated. I won't push anything till you confirm.

**Comment by BackSlasher** [comment]
Push to this branch as you please, worst case scenario I'll rebase it :)
That way I can test it too.
Also please amend the test cookbook to include the use case you had failing:
https://github.com/BackSlasher/chef-selinuxpolicy/tree/master/test/cookbooks/selinux_policy_test
Read more about not_if:
https://docs.chef.io/resource_common.html#not-if-examples

*Nitzan Raz*
http://backslasher.net

**Comment by equick** [comment]
I've pushed some updates which are working for me. Hope these look ok now.

**Comment by BackSlasher** [comment]
Aside from the weird issues, please add the test to the test cookbook so it's easier to test and we won't have a regression later on. LMK if you need help with that

**Comment by equick** [comment]
I can run the actual commands to show that duplicate ports (but with diff types) are possible:
```
[root@laptop chef-selinuxpolicy]# semanage port -l | grep 8020
hadoop_namenode_port_t         tcp      8020
[root@laptop chef-selinuxpolicy]# semanage port -m -t http_port_t -p tcp 8020
[root@laptop chef-selinuxpolicy]# semanage port -l | grep 8020
hadoop_namenode_port_t         tcp      8020
http_port_t                    tcp      8020, 80, 81, 443, 488, 8008, 8009, 8443, 9000
```

I guess a test like this should call the LWRP like below but I'm not sure what form you're expecting to see this test in so might need a bit more guidance from you on that.
```
selinux_policy_port '8020' do
    protocol 'tcp'
    secontext 'http_port_t'
end
```

**Comment by BackSlasher** [comment]
I'm sorry for not giving it my full attention, I'm afraid I'm pretty busy.
I'll try looking at it over the weekend.
Basically, someone contributed a test cookbook that is used by Chef Kitchen
as a way to test this cookbook's components. I wanted you to update it with
all of your passing / failing test cases so I can automatically test for
them, now and in the future. Worst ase scenario I'll add them myself.

*Nitzan Raz*
http://backslasher.net

**Comment by equick** [comment]
No probs. I haven't worked out how to run the test in your CB yet as there was no .kitchen.yml file but I'm sure if you add the following in the test recipe 
```
selinux_policy_port '8020' do
    protocol 'tcp'
    secontext 'http_port_t'
end
```
and run it with this branch it will work ok with this guard  

```
not_if port_defined(new_resource.port, new_resource.protocol)
```
but not this one
```
not_if port_defined(new_resource.port, new_resource.protocol, new_resource.secontext)
```

**Comment by BackSlasher** [comment]
@equick I made some tests (see `testing` branch). Feel free to rebase this branch against this or enrich the tests, I'll do it tomorrow hopefully.
About the script's behavior, I've decided to test it separately using some mocking framework. Hopefully I'll place it around here

**Comment by equick** [comment]
That looks cool, I just started playing around with it and get an error https://gist.github.com/equick/93ceb55ae07a43c13a4a. Were you getting that as well?

**Comment by BackSlasher** [comment]
I had a great idea and rewritten the whole thing :)
Will push soon enough hopefully

**Comment by BackSlasher** [comment]
Made redundant thanks to 06862589c15b7ca8924131231db023cb33b1ab1d

**Comment by BackSlasher** [comment]
@equick please LMK if new version (0.8.0) works OK for your case.  
It should, as it passes my testing. If not, please comment on #30

**Pull request closed without merging**
