### PR TITLE
Change yum dependency to ~> 4.0

### PR DESCRIPTION
**Pull request by chewi**
Tested against Fedora 24.

### CODE REVIEW

**Comment by BackSlasher** [comment]
Thanks for the PR. Did you get a chance to test this via the test suite?

**Comment by chewi** [comment]
Yes, the RSpec tests pass and I modified .kitchen.yml to run the test suite under Fedora 24. It passed even though you currently have Fedora listed as broken.

**Comment by BackSlasher** [comment]
I'm not sure what df I did in that fedora commit. I'll play with it a bit.

**Comment by BackSlasher** [comment]
How did you check on fedora 24?
```
index fbfe551..233e604 100644
--- a/.kitchen.yml
+++ b/.kitchen.yml
@@ -16,6 +16,7 @@ platforms:
   - name: centos-7.2
   - name: fedora-22
   - name: fedora-23
+  - name: fedora-24
```
Doesn't work for me

**Comment by chewi** [comment]
That's what I did. How did it fail?

**Comment by BackSlasher** [comment]
```
nitz@mars:~/projects/chef/selinux_policy (fedora-normalize *)$ kitchen test fedora-24
-----> Starting Kitchen (v1.10.0)
-----> Cleaning up any prior instances of <default-fedora-24>
-----> Destroying <default-fedora-24>...
       Finished destroying <default-fedora-24> (0m0.00s).
-----> Testing <default-fedora-24>
-----> Creating <default-fedora-24>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Checking if box 'bento/fedora-24' is up to date...
       ==> default: Clearing any previously set forwarded ports...
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
       Timed out while waiting for the machine to boot. This means that
       Vagrant was unable to communicate with the guest machine within
       the configured ("config.vm.boot_timeout" value) time period.
       
       If you look above, you should be able to see the error(s) that
       Vagrant had when attempting to connect to the machine. These errors
       are usually good hints as to what may be wrong.
       
       If you're using a custom box, make sure that networking is properly
       working and you're able to connect to the machine. It is a common
       problem that networking isn't setup properly in these boxes.
       Verify that authentication configurations are also setup properly,
       as well.
       
       If the box appears to be booting properly, you may want to increase
       the timeout ("config.vm.boot_timeout") value.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'bento/fedora-24' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
STDERR: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1] on default-fedora-24
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

```

**Comment by chewi** [comment]
I just tried it again, definitely working here. Your Kitchen version is older than mine (v1.13.2) but this looks more like a Vagrant (1.8.6) or VirtualBox (5.1.8) issue.

**Comment by BackSlasher** [comment]
I'll try upgrading stuff

**Comment by BackSlasher** [comment]
I tried getting fancy with something like '>=3.9, <5.0` but I think I'll grab this and that's it

**Comment by BackSlasher** [comment]
Merged in `v1.1.1` (fa3081364e5af2e1fe495fae0605b32aff43ea63)

**Pull request closed without merging**
