### PR TITLE
Support Chef 11.8

### PR DESCRIPTION
**Pull request by kierenevans**
Fixes issue #7 for our usages.

Further verification can be made in test kitchen by specifying the chef version in `.kitchen.yml`, though I have not done this for this PR.

### CODE REVIEW

**Comment by BackSlasher** [comment]
Since I don't have Chef 11 anywhere - don't you happen to have unicode/ascii mixup issues like #6 ?

**Comment by kierenevans** [comment]
I haven't had any issues like #6 but I'm running with hosted chef, which will be based on chef server 12.

I'm in the middle of setting up a test kitchen configuration to let you test on both chef 11 and chef 12.

**Comment by BackSlasher** [comment]
That'll be great.
I also see that one of your commits (57a0a61d40d18f4362e3ea7e0adc6814dc7a0dfe) completely shadows an earlier one (e6a33b93ab284dc37f8f6a4494c7cebf75ed42ae). Could you please squash?
Worst case I'll do it :)

**Comment by BackSlasher** [comment]
Sort-of-merged into master. Please LMK if I didn't merge something, and open a new issue if Chef11 still broken

**Pull request closed without merging**
