### PR TITLE
Fix for Chef 13 deprecation warning

### PR DESCRIPTION
**Pull request by equick**

### CODE REVIEW

**Comment by BackSlasher** [comment]
Just got to review it. Passed kitchen?

**Comment by equick** [comment]
Yes it passes but I'm wary that the output might not be quite as neat as you would like:

https://gist.github.com/equick/7f3e86b161727dc34f4108b2e07d4d5f

Basically the test is designed to throw an error when a bad port is passed and in this case ignore the failure. This counts as a pass. 

If selinux_policy accepts the bad port value, it will notify the ruby block.

**Comment by BackSlasher** [comment]
solves #45

**Comment by BackSlasher** [comment]
I think it looks nice. The only shame is that it's a runtime issue rather than a compilation issue. But that's a future improvement thing. Rest of the kitchen runs OK?

**Comment by equick** [comment]
Well ... not exactly :) See for yourself:

default-centos-6-chef-11 https://gist.github.com/equick/a21cb38e1f9e7fe79ad6375fbff5b825 (pass)
default-centos-67 https://gist.github.com/equick/c1fee501446a8912674393e88e8512cf (fail)
default-centos-72  https://gist.github.com/equick/605ecfe4b1da15e4694de68f59faa27d (fail)
broken-selinux-fedora-22 https://gist.github.com/equick/694ff094fe890bac50de2fecc54a157f (fail)
broken-selinux-fedora-23 https://gist.github.com/equick/bf4ce60c448b9b20e2ebb8baba873303 (fail)

**Comment by BackSlasher** [comment]
Re-patched on my branch `port-validate`. Some tests are still failing, must be some regression I didn't test somewhere

**Comment by equick** [comment]
They all pass if I comment out the fcontext.rb test.

From what I can make out, the stat test performed (like the one below) is run before the file context actually changes. Possible a timing issue or something related to the run order?
```
execute 'true' do
  not_if "stat -c %C #{dir_name} | grep #{context}"
  notifies :run, 'ruby_block[fail-mismatch]', :immediate
end
```

**Comment by BackSlasher** [comment]
Maybe change it to `echo BLA ; stat -c %C #{dir_name} | grep #{context}` and see when it prints?

**Comment by equick** [comment]
No difference - https://gist.github.com/equick/24c99af2148b1b3df3a4f75547e1f66e

**Comment by BackSlasher** [comment]
I can't really figure out what's going on there.
Can you spare some time for it please? I'm afraid of keeping on releasing with something bad in it

**Comment by equick** [comment]
No probs. I need some time to figure it out myself so bear with me on this one :)

**Comment by shortdudey123** [comment]
Appears to already be in master via https://github.com/BackSlasher/chef-selinuxpolicy/commit/387225487e4a77568c70e005a4154068153f20c3

**Comment by BackSlasher** [comment]
righto.

**Pull request closed without merging**
